select
	APPLICATION.ID,
	APPLICATION.TERM,
	APPLICATION.TYPE,
	APPLICATION.COMMENT_APPLYCANT,
	APPLICATION.CREATE_DATE,
	USER.DISPLAY_NAME as APPLICANT_DISPLAY_NAME,
	APPLICATION.STATUS
from
	APPLICATION
	inner join USER
		on APPLICATION.APPLICANT_ID = USER.ID
